bicycle/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
	(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),

    url(r'^', include('blog.urls')),
)

blog/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, DeleteView
from endless_pagination.views import AjaxListView

from views import *
from models import Post

urlpatterns = patterns('',
    url(r'^$', AjaxListView.as_view(queryset=Post.objects.order_by('-published')), name='posts_list'),
    url(r'^post/(?P<pk>\d+)/$', DetailView.as_view(model=Post), name='post_detail'),
    url(r'^post/(?P<pk>\d+)/delete/$', PostDelete.as_view(model=Post), name='post_delete'),
    url(r'^post/(?P<pk>\d+)/update/$', PostUpdate.as_view(model=Post), name='post_update'),
    url(r'^post/create/$', PostCreate.as_view(model=Post), name='post_create'),
    url(r'^incoming_email/$', email_handler),
)

blog/models.py
#coding: utf8
from django.db import models
from django.contrib.sites.models import Site
from django.utils import timezone
import re


class Post(models.Model):
	class Meta:
		verbose_name = u'пост'
		verbose_name_plural = u'посты'

	title = models.CharField(verbose_name=u'заголовок', max_length=300, blank=True)
	content = models.TextField(verbose_name=u'содержимое')
	trueness = models.CharField(verbose_name=u'точность', choices=(('A', 'pivotal'), ('B', 'plain'), ('C', 'bullshit')), default='B', max_length=1)
	published = models.DateTimeField(verbose_name=u'написан', blank=True)

	def save(self, *args, **kwargs):
		if not self.published:
			self.published = timezone.now()
		return super(Post, self).save(*args, **kwargs)

	def exempt(self):
		if self.title:
			return self.title
		elif self.content:
			return re.split(r'[?.!:]', self.content, flags=re.UNICODE)[0]

	def __unicode__(self):
		return self.exempt()

class Blog(models.Model):
	class Meta:
		verbose_name = u'настройки блога'
		verbose_name_plural = u'настройки блога'

	site = models.OneToOneField(Site)
	title = models.CharField(verbose_name=u'надпись на главной', max_length=256)
	no_post_titles = models.BooleanField(verbose_name=u'показывать заголовки постов на главной', default=True)

blog/views.py
from django.views.generic import DeleteView, UpdateView, CreateView
from django.http import HttpResponse
import html2text

from models import Post

class PostDelete(DeleteView):
	def delete(self, *args, **kwargs):
		self.object = self.get_object()
		self.object.delete()
		return HttpResponse('ok')

class PostUpdate(UpdateView):
	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		for attr_name, attr_value in request.POST.items():
			if hasattr(self.object, attr_name):
				setattr(self.object, attr_name, attr_value)
		self.object.save()
		return HttpResponse('ok')

class PostCreate(CreateView):
	def get(self, *args, **kwargs):
		self.object = None
		return self.render_to_response(context={})

def email_handler(request):
	post = Post()

	if request.POST['html'] != '': # wow wow we got formatted text
		converter = html2text.HTML2Text()
		post.content = converter.handle(request.POST['html'])
	else:
		post.content = request.POST['plain']

	post.title = request.POST['headers[Subject]']

	post.save()

	return HttpResponse('ok')

templates/blog/base.html
{% load custom_tags %}
<html>
<head>
    <link href="/static/base.css" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="/static/he.js"></script>
    <script src="/static/to-markdown.js"></script>

    <title>{% current_blog %}</title>
</head>
<body>
<header>
	<h1 class="blog-title centre">{% current_blog %}</h1>
	<span class="secondary centre" id="blog-subtitle">weblog</span>
</header>
{% block content %}
{% endblock %}
<footer>
	Powered by me, Guido van Rossum and a bunch of other guys
</footer>
</body>
</html>

templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load markdown_deux_tags %}
{% block content %}
	<div class="post {{ post.get_trueness_display }} centre">
		<a href="{% url 'post_detail' pk=post.pk %}"><span class="make-link"></span></a>
		<div class="post-header centre">
			{% if post.title %}
				<h2>{{ post.title }}</h2>
			{% endif %}
			<span class="post-published">{{ post.published|date:'j E' }}</span>
		</div>
		<div class="post-content">
			{{ post.content|markdown }}
		</div>
	</div>
{% endblock %}

templates/blog/post_form.html
{% load markdown_deux_tags %}
<html>
<head>
    <link href="/static/base.css" rel="stylesheet" type="text/css">
    <link href="/static/create.css" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="/static/he.js"></script>
    <script src="/static/to-markdown.js"></script>
</head>
<body>
	<script>
	$(document).ready(function () {
		$('.post-content').focus();
		$('.submit').click(function () {
			self = $(this);
			$('.post').fadeOut(200);
			$.ajax($(this).attr('data-url'), {
				type: 'POST',
				data: { content: toMarkdown($('.post-content').html()) },
				success: function (response) {
					$('.post-content').html('');
					$('.post').fadeIn(200);
					window.close();
				}
			});
		});
	});
	</script>
	<div class="post centre" data-trueness="A">
		<div class="post-content empty-area" contenteditable>
			
		</div>
		<div class="buttons">
			<div class="button submit" data-url="{% url 'post_create' %}">Submit</div>
<!-- 			<div class="button trueness-container">
				<div class="trueness {% if post.trueness == 'A' %}active{% endif %}" data-value="A"></div>
				<div class="trueness {% if post.trueness == 'B' %}active{% endif %}" data-value="B"></div>
				<div class="trueness {% if post.trueness == 'C' %}active{% endif %}" data-value="C"></div>
			</div> -->
		</div>
	</div>
</body>

templates/blog/post_list.html
{% extends "blog/base.html" %}
{% load endless %}
{% block content %}
	{% include "blog/post_list_page.html" %}
{% endblock %}

templates/blog/post_list_page.html
{% load markdown_deux_tags %}
{% for post in post_list %}
	<script>
	$(document).ready(function () {
		$('.button').css('opacity', 0);
		{% if user.is_staff %}
		$('.post-header').off('mouseenter mouseleave');
		$('.post-header').hover(function () {
			$(this).find('.button').animate({ opacity: 1 }, 200);
		}, function () {
			$(this).find('.button').animate({ opacity: 0 }, 200);
		});
		$('.post-delete').off('click');
		$('.post-delete').click(function (){
			self = $(this);
			$.ajax($(this).attr('data-url'), {
				type: 'POST',
				success: function (response) {
					self.parents('.post').hide(200);
				}
			});
		});
		$('.post-update').off('click');
		$('.post-update').click(function (){
			self = $(this);
			if (self.hasClass('active'))
			{
				$.ajax($(this).attr('data-url'), {
					type: 'POST',
					data: { content: toMarkdown(self.parents('.post').find('.post-content').html()) },
					success: function (response) {
						self.removeClass('active');
						self.parents('.post').find('.post-content').removeAttr('contenteditable');
					}
				});

			}
			else
			{
				self.addClass('active');
				self.parents('.post').find('.post-content').attr('contenteditable','true');
			}

		});
		$('.trueness').off('click');
		$('.trueness').click(function (){
			self = $(this);
			$.ajax($(this).parents('.trueness-container').attr('data-url'), {
				type: 'POST',
				data: { trueness: $(this).attr('data-value') },
				success: function (response) {
					self.parents('.trueness-container').find('.trueness').removeClass('active');
					self.addClass('active');
					self.parents('.post').attr('data-trueness', self.attr('data-value'));
				}
			});
		});
		{% endif %}
	});
	</script>
	<div class="post {{ post.get_trueness_display }} centre" data-trueness="{{ post.trueness }}">
		<a href="{% url 'post_detail' pk=post.pk %}"><!-- <span class="make-link"></span> --></a>
		<div class="post-header centre">
<!-- 			{% if post.title %}
				<h2>{{ post.title }}</h2>
			{% endif %} -->
			<span class="post-buttons">
				<span class="button post-update" data-url="{% url 'post_update' pk=post.pk %}">Edit</span>
				<span class="button post-delete" data-url="{% url 'post_delete' pk=post.pk %}">Delete</span>
			</span>
			<span class="secondary post-published">{{ post.published|date:'j E' }}</span>
			<div class="button trueness-container" data-url="{% url 'post_update' pk=post.pk %}">
				<div class="trueness {% if post.trueness == 'A' %}active{% endif %}" data-value="A"></div>
				<div class="trueness {% if post.trueness == 'B' %}active{% endif %}" data-value="B"></div>
				<div class="trueness {% if post.trueness == 'C' %}active{% endif %}" data-value="C"></div>
			</div>
		</div>
		<div class="post-content">
			{{ post.content|markdown }}
		</div>
		{% if post.comments %}
		<span class="secondary">{{ comments_count }}</span>
		{% endif %}
	</div>
{% endfor %}